Replace validators and dtos with Zod
alanmvarela/poc-nestjs-drizzle-postgre pull request #2
Opened 2023-06-26 18:03 UTC by alanmvarela

2023-06-26 18:24 UTC, AgusPk commented on src/cards/cards.controller.ts
>      }
is this casting necesary?

2023-06-26 18:42 UTC, ulises-jeremias requested changes
just some changes, the rest look great!!

2023-06-26 18:42 UTC, ulises-jeremias commented on package.json
> +    "test:e2e": "npm run db:startdev && jest --runInBand --config ./test/jest-e2e.json --verbose --passWithNoTests --detectOpenHandles && npm run db:stopdev",
in general we would like to keep the db:start in a separate step so then I can run the DB a single time and the tests any time

same on the start:dev command 😊

2023-06-26 18:42 UTC, ulises-jeremias commented on src/db/drizzle.provider.ts
>      migrate(this.db, {migrationsFolder: './src/db/migrations'});
```suggestion
    await migrate(this.db, { migrationsFolder });
```

and at the top of the file add something like

```ts
import path from 'path';

const migrationsFolder = path.join(__dirname, 'migrations');
```

2023-06-26 18:42 UTC, ulises-jeremias commented on src/db/drizzle.provider.ts
>      migrate(this.db, {migrationsFolder: './src/db/migrations'});
this is because we can't assume to have the migrations on SRC when doing the production build

2023-06-26 18:44 UTC, AgusPk commented on src/db/drizzle.provider.ts
>      migrate(this.db, {migrationsFolder: './src/db/migrations'});
@ulises-jeremias  #bayerLessons

2023-06-27 19:05 UTC, alanmvarela commented on src/cards/cards.controller.ts
>      }
Not it's not!, thanks for the heads up! It was just a left over of some alternative ways to validate the parameters i tried before arriving to the current one.

2023-06-27 19:05 UTC, alanmvarela commented on package.json
> +    "test:e2e": "npm run db:startdev && jest --runInBand --config ./test/jest-e2e.json --verbose --passWithNoTests --detectOpenHandles && npm run db:stopdev",
Fixed!

2023-06-27 19:06 UTC, alanmvarela commented on src/db/drizzle.provider.ts
>      migrate(this.db, {migrationsFolder: './src/db/migrations'});
Fixed!

2023-06-27 19:11 UTC, ulises-jeremias approved these changes
🔥

2023-07-05 19:52 UTC, merged